# Generated by Django 5.2 on 2026-10-03 21:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def preserve_databases_and_seed_images(apps, schema_editor):
    apps.get_model("sites", "Database").objects.update(provisioned=True)
    image = apps.get_model("sites", "DockerImage")
    for name, title, prefix, description in [
        ("alpine:latest", "Alpine", "apk add --no-cache", "A small Linux base image."),
        ("python:3.13-slim", "Python", "apt-get update && apt-get install -y", "Python with pip, for server applications."),
        ("node:22-alpine", "Node.js", "apk add --no-cache", "Node.js with npm, for server applications."),
        ("ubuntu:24.04", "Ubuntu", "apt-get update && apt-get install -y", "Ubuntu Linux with apt package installation."),
    ]:
        image.objects.get_or_create(name=name, defaults={"friendly_name": title, "is_user_visible": True, "description": description, "install_command_prefix": prefix})


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_action_user_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_user_visible', models.BooleanField(default=False)),
                ('base_install_command', models.TextField(blank=True)),
                ('install_command_prefix', models.CharField(blank=True, max_length=255)),
                ('run_script_template', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DockerImageSetupCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SitePendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('teacher_approval', models.BooleanField(default=None, null=True)),
                ('admin_approval', models.BooleanField(default=None, null=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('private_admin_comments', models.TextField(blank=True)),
                ('activity', models.CharField(max_length=32)),
                ('extra_information', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteResourceLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpus', models.FloatField(blank=True, null=True)),
                ('memory', models.CharField(blank=True, max_length=32)),
                ('max_request_body_size', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='pending_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='database',
            name='provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='admin_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='custom_nginx_config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='image_packages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='image_write_run_script',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('removing', 'Removal pending'), ('deleted', 'Deleted'), ('blocked', 'Blocked')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ty',
            field=models.CharField(choices=[('create_site', 'Creating site'), ('rename_site', 'Renaming site'), ('edit_site_names', 'Changing site name/domains'), ('change_site_type', 'Changing site type'), ('create_site_database', 'Creating site database'), ('delete_site_database', 'Deleting site database'), ('regen_site_secrets', 'Regenerating site secrets'), ('update_resource_limits', 'Updating site resource limits'), ('update_docker_image', 'Updating site Docker image'), ('delete_site', 'Deleting site'), ('restart_site', 'Restarting site'), ('fix_site', 'Attempting to fix site'), ('regen_nginx_config', 'Updating routing configuration')], max_length=24, verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('domain'), condition=models.Q(('status__in', ['active', 'inactive', 'blocked', 'removing'])), name='unique_reserved_domain'),
        ),
        migrations.AddField(
            model_name='site',
            name='docker_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.dockerimage'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='setup_commands',
            field=models.ManyToManyField(blank=True, to='sites.dockerimagesetupcommand'),
        ),
        migrations.AddField(
            model_name='sitependinguser',
            name='sites',
            field=models.ManyToManyField(related_name='pending_users', to='sites.site'),
        ),
        migrations.AddField(
            model_name='siterequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteresourcelimits',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_limits', to='sites.site'),
        ),
        migrations.RunPython(preserve_databases_and_seed_images, migrations.RunPython.noop),
    ]
