# Generated by Django 5.2 on 2026-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_dockerimage_dockerimagesetupcommand_sitependinguser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='ty',
            field=models.CharField(choices=[('create_site', 'Creating site'), ('rename_site', 'Renaming site'), ('edit_site_names', 'Changing site name/domains'), ('change_site_type', 'Changing site type'), ('create_site_database', 'Creating site database'), ('delete_site_database', 'Deleting site database'), ('regen_site_secrets', 'Regenerating site secrets'), ('update_resource_limits', 'Updating site resource limits'), ('update_docker_image', 'Updating site Docker image'), ('delete_site', 'Deleting site'), ('restart_site', 'Restarting site'), ('fix_site', 'Attempting to fix site'), ('regen_nginx_config', 'Updating routing configuration'), ('update_availability', 'Updating public access')], max_length=24, verbose_name='type'),
        ),
    ]
