[project]
name = "Orchestrator"
version = "0.1.0"
description = "A next generation website hosting platform"
dependencies = [
  "docker",
  "fastapi[standard]",
  "jinja2",
  "pydantic",
  "pydantic-extra-types",
  "psycopg[binary]",
  "PyMySQL",
  "requests",
  "typing-extensions",
]

[dependency-groups]
lint = [
  "mypy",
  "pre-commit",
  "types-PyMySQL",
  "types-requests",
]
test = [
  "httpx",
  "pytest",
  "pytest-xdist",
]

[tool.uv]
package = false
default-groups = ["lint", "test"]
