# Generated by Django 5.2 on 2026-10-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_service_massemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemail',
            name='recipient_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
