"""Django settings for Director project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import socket
from pathlib import Path
from typing import Final

from . import types

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yr31n(-7zgl2=i@pq5istf+i(nh3fryf5xn7l_=(y1$@=oh!is"
DIRECTOR_APPSERVER_TOKEN = os.environ.get("DIRECTOR_APPSERVER_TOKEN", "")
DIRECTOR_SSH_HOST = os.environ.get("DIRECTOR_SSH_HOST", "localhost")
DIRECTOR_SSH_PORT = int(os.environ.get("DIRECTOR_SSH_PORT", "2222"))
DIRECTOR_SSH_HOST_KEY = os.environ.get("DIRECTOR_SSH_HOST_KEY", "")
FORBIDDEN_SITE_NAME_REGEX = r"(?!)"
BLACKLISTED_SITE_NAMES = []
BLACKLISTED_SITE_REGEXES = []
WHITELISTED_SITE_NAMES = []
DIRECTOR_REQUIRE_GUIDELINES = True
DIRECTOR_SITE_STORAGE_SHARED = True
DIRECTOR_CONTACT_EMAIL = "director@tjhsst.edu"
DIRECTOR_MANAGER_URL = os.environ.get("DIRECTOR_MANAGER_URL", "http://localhost:8080")
DIRECTOR_GUIDELINES_URL = "/guidelines/"
DIRECTOR_METRICS_SCRAPE_IPS = []

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("DIRECTOR_CACHE_URL", "redis://redis:6379/2"),
    }
}

DEBUG = True

ALLOWED_HOSTS = [
    "director.tjhsst.edu",
    "localhost",
    ".local",
    "127.0.0.1",
]

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_linear_migrations",
    "social_django",
    "director.apps.auth",
    "director.apps.users",
    "director.apps.sites",
    "director.apps.marketplace",
    "heroicons",
    "django_htmx",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "director.apps.sites.governance.GuidelinesMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "director.apps.auth.middleware.IonAuthExceptionMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "director.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "director.apps.context_processors.generic_info",
                "director.apps.sites.governance.governance_context",
            ],
            "builtins": [
                "heroicons.templatetags.heroicons",
            ],
        },
    },
]
WSGI_APPLICATION = "director.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "postgres",
        "PORT": "5432",
        "NAME": "director",
        "USER": "director",
        "PASSWORD": "director",
    },
}

TESTING = "PYTEST_VERSION" in os.environ or "CI" in os.environ

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ["director.apps.auth.oauth.IonOauth2"]

SOCIAL_AUTH_USER_FIELDS = [
    "username",
    "first_name",
    "last_name",
    "email",
    "id",
    "is_teacher",
    "is_student",
    "graduation_year",
]

SOCIAL_AUTH_URL_NAMESPACE = "social"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "director.apps.auth.oauth.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "director.apps.auth.oauth.sync_graduation_year",
    "director.apps.auth.oauth.attach_pending_sites",
)

AUTH_USER_MODEL = "users.User"


LOGIN_REDIRECT_URL = "/"

SOCIAL_AUTH_LOGIN_ERROR_URL = "auth:login"
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Django Debug Toolbar
_enabled_panels = {
    "debug_toolbar.panels.history.HistoryPanel",
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
    "debug_toolbar.panels.profiling.ProfilingPanel",
}

DEBUG_TOOLBAR_CONFIG = {
    "DISABLE_PANELS": _enabled_panels,
    "SHOW_COLLAPSED": True,
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "collected_static"

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ASGI for websockets
ASGI_APPLICATION = "director.asgi.application"


# Celery
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_LOG_LEVEL = "WARNING"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}


# Director settings
DOCS_URL = "https://jasongrace2282.github.io/director5/"
REPO_URL = "https://github.com/jasongrace2282/director5/"
CONTACT_EMAIL = "director@tjhsst.edu"

# The URL that will be used for various site types.
# The site name is interpolated into this using str.format(). It is guaranteed to be
# URL/domain-safe.
# The key indicates that this format should be used for a given site "purpose" (e.g. the "user"
# URL is used for user sites). The "None" key indicates the default format if there is not an
# explicit entry for a given site's "purpose" (and it MUST be specified).
SITE_URL_FORMATS = {
    "user": "user.localhost/{}/",
    "activity": "activities.localhost/{}/",
    None: "{}.sites.localhost",
}


# Fractions of a CPU
DIRECTOR_RESOURCES_DEFAULT_CPUS: Final = 0.6
# Memory in bytes
DIRECTOR_RESOURCES_DEFAULT_MEMORY_LIMIT: Final = 100 * 1000 * 1000
# Client body (aka file upload) size limit in bytes
DIRECTOR_RESOURCES_MAX_REQUEST_BODY: Final = 2 * 1024 * 1024

# Appservers
DIRECTOR_APPSERVER_HOSTS: list[str] = ["fastapi:8080"]

DIRECTOR_APPSERVER_SSL: types.SSLSettings | None = None
"""Whether to use HTTP or HTTPS.

Uses HTTP if is ``None``. Note that the SSL settings must be the same
for all appservers (by design).
"""

# These options control what is removed when a site is deleted.
# If SITE_DELETION_REMOVE_FILES is True, all of the site's files are removed. (It
# may make sense to set this to False so users' files can be recovered later, though
# the site ID would need to be known.)
# If SITE_DELETION_REMOVE_DATABASE is True, the site's database is removed. (It is
# strongly recommended to leave this as True to avoid clogging up the database
# server.)
SITE_DELETION_REMOVE_FILES: Final = True
SITE_DELETION_REMOVE_DATABASE: Final = True

# Apply deployment settings after all defaults so production values are retained.
# Only an absent secret module is optional; errors inside it must stop startup.
try:
    from .secret import *  # noqa: F403
except ModuleNotFoundError as exc:
    if exc.name != f"{__package__}.secret":
        raise

if DEBUG:
    INSTALLED_APPS += ["django_extensions", "debug_toolbar", "django_browser_reload"]
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    AUTHENTICATION_BACKENDS.append("django.contrib.auth.backends.ModelBackend")
    # Docker creates IP addresses dynamically; permit its gateway for debug tools.
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]

# Tests must never connect to the configured production database.
if TESTING:
    DATABASES["default"]["ENGINE"] = "django.db.backends.sqlite3"
    DATABASES["default"]["NAME"] = ":memory:"
